"""Prompt compiler v1 — FROZEN once released.

Same preset in, same prompt out, forever. The JS port in widget/src/compiler.js
must produce byte-identical output; both run against core/tests/golden/.
Do not edit this file after release — add a v2 compiler instead.
"""

from __future__ import annotations

from core.constants import CLOSING_LINE, LAYOUTS, RESTRICTION_PRESETS
from core.schema import Preset

COMPILER_VERSION = 1


def compile_v1(preset: Preset) -> str:
    parts: list[str] = []

    size = preset.size
    label = f" ({size.aspect_label})" if size.aspect_label else ""
    parts.append(f"Output format: {size.width}x{size.height} pixels{label}.")

    parts.append(f"Layout pattern: {LAYOUTS[preset.layout]}")

    element_lines: list[str] = []
    for el in preset.elements:
        content = el.content.strip()
        if not content:
            continue
        if el.kind == "text":
            element_lines.append(
                f'  - "{content}" (text) -> positioned at {el.zone}'
            )
        else:
            element_lines.append(
                f"  - {content} (subject) -> positioned at {el.zone}"
            )
    if element_lines:
        parts.append("Element placement:\n" + "\n".join(element_lines))

    style = preset.style
    style_bits: list[str] = []
    if style.art_style:
        style_bits.append(f"art style: {style.art_style.strip()}")
    if style.palette:
        style_bits.append("color palette: " + " ".join(style.palette))
    if style.typography:
        style_bits.append(f"typography: {style.typography.strip()}")
    if style.lighting:
        style_bits.append(f"lighting: {style.lighting.strip()}")
    if style_bits:
        parts.append("Visual style — " + ", ".join(style_bits) + ".")

    restriction_bits: list[str] = []
    for key in preset.restrictions:
        phrase = RESTRICTION_PRESETS.get(key, key.strip())
        if phrase:
            restriction_bits.append(phrase)
    if restriction_bits:
        parts.append("Do NOT include: " + ", ".join(restriction_bits) + ".")

    if preset.free_text and preset.free_text.strip():
        parts.append("Additional details:\n" + preset.free_text.strip())

    parts.append(CLOSING_LINE)
    return "\n\n".join(parts)
