"""Prompt compiler v2 — FROZEN once released.

A superset of v1: for presets with only text/subject elements the output is
byte-identical to v1. When product/background elements are present, an
"Input images" section is inserted (after the layout, before element
placement) describing the photos the user will attach at generation time.

The JS port in widget/src/compiler.js must produce byte-identical output;
both run against core/tests/golden/. Do not edit this file after release —
add a v3 compiler instead.
"""

from __future__ import annotations

from core.constants import (
    BACKGROUND_DIRECTIVE,
    CLOSING_LINE,
    LAYOUTS,
    PRODUCT_ALL_OVER,
    PRODUCT_DIRECTIVE,
    RESTRICTION_PRESETS,
)
from core.schema import Preset

COMPILER_VERSION = 2


def compile_v2(preset: Preset) -> str:
    parts: list[str] = []

    size = preset.size
    label = f" ({size.aspect_label})" if size.aspect_label else ""
    parts.append(f"Output format: {size.width}x{size.height} pixels{label}.")

    parts.append(f"Layout pattern: {LAYOUTS[preset.layout]}")

    # Input images — products & backgrounds, in the order the user attaches them.
    image_lines: list[str] = []
    n = 0
    for el in preset.elements:
        if el.kind not in ("product", "background"):
            continue
        n += 1
        content = (el.content or "").strip()
        hint = f' ("{content}")' if content else ""
        if el.kind == "product":
            placement = (
                PRODUCT_ALL_OVER if el.zone == "all-over" else f"placed at {el.zone}"
            )
            image_lines.append(
                f"  - Attached image {n} = PRODUCT{hint} -> {placement}, "
                f"{PRODUCT_DIRECTIVE}."
            )
        else:  # background
            image_lines.append(
                f"  - Attached image {n} = BACKGROUND{hint} -> {BACKGROUND_DIRECTIVE}."
            )
    if image_lines:
        parts.append(
            "Input images (the user will attach these, in order):\n"
            + "\n".join(image_lines)
        )

    # Element placement — text/subject only (identical wording to v1).
    element_lines: list[str] = []
    for el in preset.elements:
        if el.kind not in ("text", "subject"):
            continue
        content = el.content.strip() if el.content else ""
        if not content:
            continue
        if el.kind == "text":
            element_lines.append(
                f'  - "{content}" (text) -> positioned at {el.zone}'
            )
        else:
            element_lines.append(
                f"  - {content} (subject) -> positioned at {el.zone}"
            )
    if element_lines:
        parts.append("Element placement:\n" + "\n".join(element_lines))

    style = preset.style
    style_bits: list[str] = []
    if style.art_style:
        style_bits.append(f"art style: {style.art_style.strip()}")
    if style.palette:
        style_bits.append("color palette: " + " ".join(style.palette))
    if style.typography:
        style_bits.append(f"typography: {style.typography.strip()}")
    if style.lighting:
        style_bits.append(f"lighting: {style.lighting.strip()}")
    if style_bits:
        parts.append("Visual style — " + ", ".join(style_bits) + ".")

    restriction_bits: list[str] = []
    for key in preset.restrictions:
        phrase = RESTRICTION_PRESETS.get(key, key.strip())
        if phrase:
            restriction_bits.append(phrase)
    if restriction_bits:
        parts.append("Do NOT include: " + ", ".join(restriction_bits) + ".")

    if preset.free_text and preset.free_text.strip():
        parts.append("Additional details:\n" + preset.free_text.strip())

    parts.append(CLOSING_LINE)
    return "\n\n".join(parts)
